#! /bin/bash

./RunAExperiment.sh fat_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.0 1.0 result-10/fat_table_output_insertonly.dat &> result-10/RunAExperiment_insertonly_1.log
#./RunAExperiment.sh fat_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.1 0.9 result-10/fat_table_output_1.dat &> result-10/RunAExperiment_1.log
#./RunAExperiment.sh fat_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.3 0.7 result-10/fat_table_output_2.dat &> result-10/RunAExperiment_2.log
#./RunAExperiment.sh fat_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.5 0.5 result-10/fat_table_output_3.dat &> result-10/RunAExperiment_3.log
#./RunAExperiment.sh fat_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.7 0.3 result-10/fat_table_output_4.dat &> result-10/RunAExperiment_4.log
#./RunAExperiment.sh fat_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.9 0.1 result-10/fat_table_output_5.dat &> result-10/RunAExperiment_5.log


./RunAExperiment.sh thin_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.0 1.0 result-10/thin_table_output_insertonly.dat &>result-10/RunAExperiment_insertonly_2.log
#./RunAExperiment.sh thin_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.1 0.9 result-10/thin_table_output_1.dat &>result-10/RunAExperiment_6.log
#./RunAExperiment.sh thin_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.3 0.7 result-10/thin_table_output_2.dat &> result-10/RunAExperiment_7.log
#./RunAExperiment.sh thin_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.5 0.5 result-10/thin_table_output_3.dat &> result-10/RunAExperiment_8.log
#./RunAExperiment.sh thin_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.7 0.3 result-10/thin_table_output_4.dat &> result-10/RunAExperiment_9.log
#./RunAExperiment.sh thin_table_workload /home/hadoop/git/schema_design/script/drop_usertable.sql /home/hadoop/git/schema_design/script/create_user_table1.sql 0.9 0.1 result-10/thin_table_output_5.dat &> result-10/RunAExperiment_10.log
